version: "3.7"

networks:
  moisklad_global:
    attachable: true

services:
  app:
    build:
      args:
        user: webuser
        uid: 1000
      context: ./docker/php/8.2/
      dockerfile: Dockerfile
    image: moisklad-php-8-2
    working_dir: /var/www/
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
      XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug,coverage}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: 'yes'
    volumes:
      - ./:/var/www
      - ./docker/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - moisklad_global

  db:
    image: mysql:5.7
    #    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    networks:
      - moisklad_global

  nginx:
    image: nginx:alpine
    #    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - moisklad_global

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - moisklad_global

  memcached:
    image: memcached
    ports:
      - "11211"
    volumes:
      - ./:/var/www
    networks:
      - moisklad_global

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - moisklad_global
